title       = "xueqiu"
baseURL     = "https://xueqiu-cli.tamnd.com/"
description = "A command line for Xueqiu stock community."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/xueqiu-cli"
